# Generated by Django 4.2.6 on 2023-11-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Enter your film name')),
                ('description', models.TextField(blank=True, verbose_name='Enter disctiption on this film')),
                ('images', models.ImageField(upload_to='films/')),
                ('cost', models.PositiveIntegerField(verbose_name='Enter your price')),
                ('genres', models.CharField(choices=[('Horror', 'Horror'), ('Comedy', 'Comedy')], max_length=100, verbose_name='Enter your genre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
