# Generated by Django 4.2.6 on 2023-11-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Введите имя')),
                ('age', models.PositiveIntegerField(verbose_name='Введите ваш возраст')),
                ('hobby', models.TextField(verbose_name='Укажите ваше хобби')),
                ('gender', models.CharField(choices=[('M', 'M'), ('Ж', 'Ж'), ('Не определился(ась)', 'Не определился(ась)')], max_length=100)),
                ('phone_number', models.CharField(default='+996', max_length=14, verbose_name='Ваш номер')),
            ],
        ),
    ]
